spring.application.name=bank
server.servlet.context-path=/bank-management
server.port=8084
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Pratham@9891
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
jwt.token.prefix=Bearer
jwt.private.key=wn0GSOkq62sJ4IgnX8W1nNLpqpJ8apFOIX2Wv3ZszQETj1R2Zq
spring.jpa.hibernate.ddl-auto=update